# Generated by Django 5.2.4 on 2025-08-01 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Litros')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Semanal'), (2, 'Mensal')], default=1, verbose_name='Tipo')),
                ('cadastrado_por', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
            ],
        ),
    ]
