# Generated by Django 5.2.4 on 2025-08-01 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('placa', models.CharField(max_length=150, verbose_name='Placa')),
                ('combustivel', models.PositiveSmallIntegerField(choices=[(1, 'Gasolina'), (2, 'Diesel S10'), (3, 'Alcool')], default=1, verbose_name='Tipo')),
                ('cadastrado_por', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
                ('cota', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='controle.cota', verbose_name='Cota')),
            ],
        ),
    ]
