# Generated by Django 5.2.4 on 2025-08-01 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_veiculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('justificativa', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Justificativa')),
                ('cadastrado_por', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle.veiculo', verbose_name='Veiculo')),
            ],
        ),
    ]
