# Generated by Django 5.2.4 on 2025-08-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_abastecimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cota',
            name='cadastrado_por',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='cadastrado_por',
        ),
    ]
