# Generated by Django 5.2.4 on 2025-08-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_remove_cota_cadastrado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='cota_qnt',
            field=models.IntegerField(default=1, verbose_name='N Abastecimentos'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=150, unique=True, verbose_name='Placa'),
        ),
    ]
