# Generated by Django 5.2.5 on 2025-08-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0005_veiculo_cota_qnt_alter_veiculo_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='cod_veiculo',
            field=models.IntegerField(default=1, unique=True, verbose_name='ID Veículo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='combustivel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Gasolina'), (2, 'Diesel S10'), (3, 'Fles e Semelhantes'), (4, 'Outros')], default=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Placa'),
        ),
    ]
