# Generated by Django 5.2.5 on 2025-08-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0006_veiculo_cod_veiculo_alter_veiculo_combustivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='combustivel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Gasolina'), (2, 'Diesel'), (3, 'Flex e Semelhantes'), (4, 'Outros')], default=1, verbose_name='Tipo'),
        ),
    ]
