# Generated by Django 5.2.5 on 2025-08-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0007_alter_veiculo_combustivel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abastecimento',
            options={'ordering': ['-cadastrado_em'], 'verbose_name': 'Abastecimento', 'verbose_name_plural': 'Abastecimentos'},
        ),
        migrations.AlterModelOptions(
            name='cota',
            options={'ordering': ['nome'], 'verbose_name': 'Cota', 'verbose_name_plural': 'Cotas'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['descricao'], 'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='alterado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Alteração'),
        ),
        migrations.AddField(
            model_name='cota',
            name='alterado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Alteração'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='alterado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Alteração'),
        ),
    ]
