# Generated by Django 5.2.5 on 2025-08-15 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0008_alter_abastecimento_options_alter_cota_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('secretaria', models.CharField(max_length=150, verbose_name='Secretaria')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
                'ordering': ['secretaria'],
            },
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='secretaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='controle.secretaria', verbose_name='Secretaria'),
            preserve_default=False,
        ),
    ]
