# Generated by Django 5.2.5 on 2025-08-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0009_secretaria_abastecimento_secretaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='RENAVAM'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Placa'),
        ),
    ]
