# Generated by Django 5.2.5 on 2025-08-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0010_veiculo_renavam_alter_veiculo_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RENAVAM'),
        ),
    ]
