# Generated by Django 5.2.5 on 2025-08-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0011_alter_veiculo_renavam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='RENAVAM'),
        ),
        migrations.AddConstraint(
            model_name='veiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('placa', None), _negated=True), fields=('placa',), name='unique_placa_not_null'),
        ),
        migrations.AddConstraint(
            model_name='veiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('renavam', None), _negated=True), fields=('renavam',), name='unique_renavam_not_null'),
        ),
    ]
